trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  REPO: 'https://dev.azure.com/guntupallib/baladev/_git/repo-3'
  BRANCH: 'main'  # or your branch name
  FOLDER_TO_COPY: 'bala'
  CLONE_DIR: 'cloned-repo'
  PAT: $(pat_access)  # Use th
  
steps:
- checkout: self

- bash: |
   mkdir bala
   cd bala
   echo "This is the content of file.txt" > file.txt
   cd ..
  displayName: 'Bash Script'

- script: |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git clone $(REPO) $(CLONE_DIR)
    cp -r $(FOLDER_TO_COPY) $(CLONE_DIR)
    cd $(CLONE_DIR)
    git add .
    git commit -m "Add folder to repository"
    git push https://$(PAT)@dev.azure.com/guntupallib/baladev/_git/repo-3 HEAD:$(BRANCH)
  displayName: 'Copy folder to repository'
  env:
    GIT_SSL_NO_VERIFY: true  # This might be needed if you have SSL verification issues
